### ISSUE TITLE
Issue resolving Cake.Frosting.CLI nuget package

### ISSUE THREAD

**Issue by ryangribble** [cake-build/frosting#12]
Even with the nuget.config file containing the custom myget feeds, it seems that the package reference to `    "Cake.Frosting.CLI": "0.1.0-alpha0034"` cannot be resolved:

![image](https://cloud.githubusercontent.com/assets/5425163/18919542/ee69e5f4-85e1-11e6-9248-91d760822f3c.png)

This would appear to be confirmed by manually browsing those feeds through the webUI and also finding no reference to this package.

Simply removing it from the `project.json` tools section, everything seems to restore and run just fine, so not sure what it is actually for?

```
  "tools": {
    "Cake.Frosting.CLI": "0.1.0-alpha0034"
  }
```

**Comment by patriksvensson** [comment]
@ryangribble Are you by any chance running this on OS X?

**Comment by patriksvensson** [comment]
Ok, realized that you're runing Windows by your screenshot. Sorry!

Version 35 should exist. Can you try that one?

**Comment by ryangribble** [comment]
Yeah I tried 35 as well. 

Which myget feed is it in? I couldn't find it in the myget feed's website either...  Maybe it's a permissions issue? 

Eg this works 
https://www.myget.org/feed/cake/package/nuget/Cake.Frosting

But this (taking a guess on the url) kicks me back out to my myget welcome/profile page 
https://www.myget.org/feed/cake/package/nuget/Cake.Frosting.CLI

dotnet restore and run work without this anyway, is this what provides the `dotnet cake` command (which doesn't work for me currently)?

**Comment by patriksvensson** [comment]
Hmm, will investigate later today when I'm at a computer and get back to you.

**Comment by patriksvensson** [comment]
And yes, CLI is what gives you the `dotnet cake` command :smile:

**Comment by patriksvensson** [comment]
@ryangribble There seems to have been some problem on MyGet. I've probably managed to delete the package feed for Cake.Frosting.CLI somehow. I've kicked the last build again so it should work now.

Can you give it another try and see if it worked?
You might have to remove your `project.json.lock` first.

Thanks!

**Comment by ryangribble** [comment]
Yep all good now!  Both 34 and 35 are in the feed and the [above URL](https://www.myget.org/feed/cake/package/nuget/Cake.Frosting.CLI) now works :+1:

Also didnt need to delete the lock file FYI since that package hadnt been resolved yet

![image](https://cloud.githubusercontent.com/assets/5425163/18933711/612e7f00-8619-11e6-8100-0a12a7e31a78.png)

**Comment by patriksvensson** [comment]
Perfect! Sorry for the inconvenience.

**Comment by ryangribble** [comment]
All good 😀 

Ive also found the dogfooded "build frosting WITH frosting" build project to be very helpful and have pretty much copied the entire thing for the project im looking at using cake.frosting on!

**Comment by patriksvensson** [comment]
@ryangribble Awesome! :smile:

There might be some changes in the API since it's not even 0.1.0 "stable" yet, but I will try to keep the changes to a minimum if possible. If you have any questions about Frosting, feel free to contact me here, Gitter or Twitter and I will try to help you as much as I can.
