### ISSUE TITLE
Keep existing cake syntax

### ISSUE THREAD

**Issue by xclayl** [cake-build/frosting#14]
I'm really excited by this project.  

Hopefully we can use the existing syntax though. This is fairly verbose:
```

[TaskName("Provide-Another-Name-Like-This")]
public class Build : FrostingTask<MySettings>
{
    public override void Run(MySettings context)
    {
        context.Information("Magic: {0}", context.Magic);
    }
}
```

In comparison to:

```
Task("Provide-Another-Name-Like-This")
.Does(() => {
Information("Magic: {0}", context.Magic);
});
```

**Comment by patriksvensson** [comment]
At the moment we want to keep the syntax we defined even if it's verbose.

We might however add some convenience addins to Frosting to allow something like you want, but that will likely be somehing built on top of the current solution.

**Comment by xclayl** [comment]
Understandable.  Looking forward to it..
