### ISSUE TITLE
Planning on pushing a nuget version?

### ISSUE THREAD

**Issue by ryangribble** [cake-build/frosting#38]
Hey guys, we are happily using Cake.Frosting for https://github.com/octokit/octokit.net builds now.  

Are there any plans to push a non alpha build to nuget?  Things are working great from our perspective :+1:

**Comment by patriksvensson** [comment]
@ryangribble Yes, there is plans of pushing a NuGet version soon. We still need to finish up some issues, but I've put aside some time during the summer for this.

**Comment by amoerie** [comment]
Any status update on this?

**Comment by clmcgrath** [comment]
the 0.31.0  package is now live on nuget,  guessing this can be closed now ?

**Comment by devlead** [comment]
Yip
