### ISSUE TITLE
Add SubTask Support

### ISSUE THREAD

**Issue by lennoncork** [cake-build/frosting#54]
It  might be nice if the Frosting Task supported multiple sub-tasks through the use of attributes. Akin to the NUnit test runner where multiple tests can exist in a parent fixture. I think this would make it easier to support async tasks requested in #45. 

A simple prototype might be to implement another base class that inherits from FrostingTask<Context> and does the reflection over itself to identify the appropriate attributes. Overriding the run method would then simply be calling each discovered method. 

Thoughts?

**Comment by clmcgrath** [comment]
Frosting currently supports task dependencies via [Dependency(typeof(DependentTask))] and works in the same fashion as the .DenpedentOn() method in cake scripts 
does this satisfy what you are looking to accomplish ?

**Comment by gep13** [comment]
@clmcgrath @lennoncork since there hasn't been any follow up on this issue, I am going to go ahead and close it out.  If there are any concerns, please reach out.
