### ISSUE TITLE
Nuget package out of date 

### ISSUE THREAD

**Issue by clmcgrath** [cake-build/frosting#56]
Just curious if there is any particular reason that the develop branch which supports the latest cake tools 0.30 is not pushed to master currently?
the current nuget package is targeting netcore 1.x anyway we could get this pushed to nuget public feed 

if there are bugs still i understand ,  just kind of anxious to use the latest build

**Comment by devlead** [comment]
It's currently avail on MyGet
https://www.myget.org/feed/cake/package/nuget/Cake.Frosting/0.30.0

Targeting  .NETFramework 4.6.1 and .NETStandard 2.0

**Comment by clmcgrath** [comment]
awesome thanks !

**Comment by devlead** [comment]
@clmcgrath Frosting now up to date with just released version 0.31.0 of Cake
https://www.nuget.org/packages/Cake.Frosting/0.31.0

**Comment by clmcgrath** [comment]
awesome :D
