### ISSUE TITLE
Ensure dll determenistic 

### ISSUE THREAD

**Issue by devlead** [cake-build/frosting#72]
![image](https://user-images.githubusercontent.com/1647294/85850882-f96b3780-b7ad-11ea-9823-8990c9f553c5.png)

**Comment by gep13** [comment]
@devlead what exactly is this?  I haven't seen this before.

**Comment by devlead** [comment]
NuGet package explorer

**Comment by gep13** [comment]
@devlead that part I got 😄 I was referring to the actual error message.  I am assuming that we can't just add that property to the csproj file, it would need to be conditional right?  If so, how do we determine if we are actually running on CI within the csproj file?

**Comment by gep13** [comment]
Or, should we pass this as a property to `dotnet build` rather than add to the csproj file?

**Comment by devlead** [comment]
Good question 🤔it shouldn't be in csproj I guess, just passed during CI. But haven't read up on it yet.

**Comment by gep13** [comment]
Tried making a change to just include the `ContinuousIntegrationBuild` property when running on AppVeyor, but looks like there is more to it than that...

https://ci.appveyor.com/project/cakebuild/frosting/builds/33878980/job/6k4csxk5p8tgsxe8#L224

**Comment by gep13** [comment]
I have backed out the change for now.

**Comment by devlead** [comment]
Source link needed to, more info here:
https://github.com/clairernovotny/DeterministicBuilds

**Comment by gep13** [comment]
SourceLink is already included.

**Comment by gep13** [comment]
This has been addressed...

![image](https://user-images.githubusercontent.com/1271146/86409890-a6174e80-bcb1-11ea-8e2a-f4970f6a0ea7.png)
