### ISSUE TITLE
Publish packages to Azure Artifacts and NuGet

### ISSUE THREAD

**Issue by gep13** [cake-build/frosting#86]
Currently, packages are only pushed to MyGet.  Going forward, we should push pre-release packages to MyGet and then the released packages to NuGet, in the same way as we do with the Cake packages.

**Comment by devlead** [comment]
Cake we ship to Azure Artifacts and not myget, so should probably do the same with Cake.Frosting.

**Comment by gep13** [comment]
@devlead ah, that is a good point!

**Comment by devlead** [comment]
Before we push to NuGet.org #89 needs to be done as Cake packages are required to be signed.
